class SignupLocators:
    FIRST_NAME_INPUT = 'input[name="first_name"]'
    LAST_NAME_INPUT = 'input[name="last_name"]'
    EMAIL_INPUT = 'input[name="email"]'
    PASSWORD_INPUT = 'input[name="password"]'
    CONFIRM_PASSWORD_INPUT = 'input[name="password_repeat"]'
    SIGNUP_BUTTON = 'button:has-text("Sign Up")'
    ERROR_MESSAGE = '.error-message, .alert-danger, [role="alert"], .text-danger'
    SUCCESS_MESSAGE = '.success-message, .alert-success, [role="status"]'
    LOGIN_LINK = 'a:has-text("Login"), a:has-text("Sign in"), a:has-text("Already have")'
